GET https://api2.successfactors.eu/odata/v2/EmpJob?$filter=userId eq '168153' and ( startDate le '2021-03-19' and endDate ge '2021-03-19' )&$format=json
Authorization: Basic SFAPI@italgasretD:password

###
POST http://localhost:4004/media/Attachments
Content-Type: application/json

{
    "mimeType": "text/plain",
    "name": "test_app.txt",
    "pubblication_ID": "3dd1998c-aaa8-4ba8-b948-17cf5ffed616"
}