GET https://api2.successfactors.eu/odata/v2/EmpJob?$filter=userId eq 'SPGRMN80L45C816L' and ( startDate le '2021-03-26' and endDate ge '2021-03-26' )&$format=json&$orderBy=startDate desc,seqNumber desc
Authorization: Basic SFAPI@italgasretD:password

###
POST http://localhost:4004/media/Attachments
Content-Type: application/json

{
    "mimeType": "text/plain",
    "name": "test_app.txt",
    "pubblication_ID": "3dd1998c-aaa8-4ba8-b948-17cf5ffed616"
}